sonar.projectKey=sonarnode10326
sonar.projectName=sonarnode10326
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.exclusions=**/node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
